#!/bin/bash

export SCALA_HOME=/usr/share/scala/:/usr/local/opt/scala/idea
export PATH=$PATH:$SCALA_HOME

if [ ! $SCALA_HOME ]
then
    echo ERROR: set a SCALA_HOME environment variable
    exit
fi

command -v scalac >/dev/null 2>&1 || { echo >&2 "ERROR: 'scalac' not found"; exit 1; }
command -v scala >/dev/null 2>&1 || { echo >&2 "ERROR: 'scala' not found"; exit 1; }


if [ ! -f scala-library.jar ]
then
    cp $SCALA_HOME/lib/scala-library.jar .
fi

scalac -sourcepath src -d bin src/$1.scala

cd bin
jar -cfm ../$1.jar ../MANIFEST.MF *
cd ..

scala -cp . $1.jar

now=$(date +"%s%N")
mkdir -p ../../history/$1
cp ./src/$1.scala ../../history/$1/$now